import { buildKitchenPlan } from "./src/layout/plan-model.js";
import { generateLayout } from "./src/layout/generate.js";
import { auditDeliverable } from "./src/delivery/audit.js";
import { addWallRun, addFeature, createFloorPlan } from "./src/floorplan/parse.js";
import { pilotModules } from "./src/app/seed.js";
import { applianceFrom } from "./src/floorplan/appliances.js";
const appliances = [applianceFrom({ kind: "refrigerator", width: 33 }), applianceFrom({ kind: "range", width: 30 })];
const at = "2026-01-01T00:00:00.000Z";
let fp = await createFloorPlan({ conversationId:"c", at, file:{name:"k.png",mimeType:"image/png",sizeBytes:1} } as any, undefined, undefined);
for (const [label,len] of [["南墙",120],["东墙",120],["北墙",120],["西墙",120]] as const) fp = addWallRun(fp, {label,length:len}, at);
const runs = fp.parsedGeometry.wallRuns;
fp = addFeature(fp, runs[0]!.id, { kind:"door", offset:40, width:32 }, at);
fp = addFeature(fp, runs[1]!.id, { kind:"plumbing", offset:50, width:24 }, at);
const g = { ...fp.parsedGeometry, ceilingHeight: 96 };
console.log(g.wallRuns.map(r=>`${r.label} s=${r.startsAtCorner} e=${r.endsAtCorner}`));
const plan = buildKitchenPlan(g);
console.log("connected", plan.connected, "corners", plan.corners.length);
for (const r of plan.runs) console.log(r.run.label, r.origin, r.heading);
const layout = generateLayout(g, pilotModules, { ceilingHeight: 96, appliances });
const rep = auditDeliverable({ deliverable:"planView", stage:"planReview", layout, wallRuns: g.wallRuns } as any);
console.log("audit ok", rep.ok);
console.log(rep.blockers.map((b:any)=>b.code+" | "+b.message));
